#ifndef COMPILEFORGE_REPORTING_TERMINAL_REPORTER_HPP
#define COMPILEFORGE_REPORTING_TERMINAL_REPORTER_HPP

#include <compileforge/reporting/report.hpp>

#endif // COMPILEFORGE_REPORTING_TERMINAL_REPORTER_HPP
